// Generated by pnpm api:generate. Do not edit by hand.

import { z } from 'zod';

export const workerSessionStates = [
  'working',
  'prompt',
  'triage',
  'done',
] as const;
export const workerSessionStateSchema = z.enum(workerSessionStates);
export type WorkerSessionState = z.infer<typeof workerSessionStateSchema>;

export const terminalSessionKinds = ['orchestrator', 'worker'] as const;
export const terminalSessionKindSchema = z.enum(terminalSessionKinds);
export type TerminalSessionKind = z.infer<typeof terminalSessionKindSchema>;

export const projectOrchestratorSchema = z.object({
  cwd: z.string().optional(),
  id: z.string(),
  name: z.string(),
});
export type ProjectOrchestrator = z.infer<typeof projectOrchestratorSchema>;

export const workerSessionSchema = z.object({
  agent: z.string(),
  agentPluginId: z.string().optional(),
  cwd: z.string().optional(),
  description: z.string(),
  id: z.string(),
  issue: z.string(),
  kind: terminalSessionKindSchema.optional(),
  metadata: z.string(),
  project: z.string(),
  selected: z.boolean().optional(),
  state: workerSessionStateSchema,
  terminalSupported: z.boolean().optional(),
  title: z.string(),
  workerId: z.string(),
  zellijSession: z.string().optional(),
});
export type WorkerSession = z.infer<typeof workerSessionSchema>;
export type WorkerAgent = WorkerSession['agent'];

export const sessionWorkspaceSchema = z.object({
  activeProjectId: z.string(),
  orchestrators: z.array(workerSessionSchema).optional(),
  projects: z.array(projectOrchestratorSchema),
  sessions: z.array(workerSessionSchema),
});
export type SessionWorkspace = z.infer<typeof sessionWorkspaceSchema>;
