/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTerminalSessionIdRouteImport } from './routes/_app.terminal.$sessionId'
import { Route as AppBoardProjectIdRouteImport } from './routes/_app.board.$projectId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalSessionIdRoute = AppTerminalSessionIdRouteImport.update({
  id: '/terminal/$sessionId',
  path: '/terminal/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardProjectIdRoute = AppBoardProjectIdRouteImport.update({
  id: '/board/$projectId',
  path: '/board/$projectId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/board/$projectId': typeof AppBoardProjectIdRoute
  '/terminal/$sessionId': typeof AppTerminalSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/board/$projectId': typeof AppBoardProjectIdRoute
  '/terminal/$sessionId': typeof AppTerminalSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/board/$projectId': typeof AppBoardProjectIdRoute
  '/_app/terminal/$sessionId': typeof AppTerminalSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board/$projectId' | '/terminal/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board/$projectId' | '/terminal/$sessionId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/board/$projectId'
    | '/_app/terminal/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terminal/$sessionId': {
      id: '/_app/terminal/$sessionId'
      path: '/terminal/$sessionId'
      fullPath: '/terminal/$sessionId'
      preLoaderRoute: typeof AppTerminalSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board/$projectId': {
      id: '/_app/board/$projectId'
      path: '/board/$projectId'
      fullPath: '/board/$projectId'
      preLoaderRoute: typeof AppBoardProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppBoardProjectIdRoute: typeof AppBoardProjectIdRoute
  AppTerminalSessionIdRoute: typeof AppTerminalSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppBoardProjectIdRoute: AppBoardProjectIdRoute,
  AppTerminalSessionIdRoute: AppTerminalSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
