//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"reflect"
	"strings"

	"github.com/yyovil/better-ao/internal/session"
)

const outputPath = "web/src/features/home/domain/session-workspace-contract.generated.ts"

type fieldSchema struct {
	Name     string
	Optional bool
	Schema   string
}

func main() {
	source, err := renderContract()
	if err != nil {
		panic(err)
	}

	if err := os.WriteFile(outputPath, []byte(source), 0o644); err != nil {
		panic(err)
	}
}

func renderContract() (string, error) {
	projectFields, err := schemaFields(reflect.TypeOf(session.Project{}))
	if err != nil {
		return "", err
	}
	sessionFields, err := schemaFields(reflect.TypeOf(session.Session{}))
	if err != nil {
		return "", err
	}
	workspaceFields, err := schemaFields(reflect.TypeOf(session.Workspace{}))
	if err != nil {
		return "", err
	}

	var out bytes.Buffer
	out.WriteString("// Generated by pnpm api:generate. Do not edit by hand.\n\n")
	out.WriteString("import { z } from 'zod';\n\n")
	writeStringEnum(&out, "workerSessionStates", "workerSessionStateSchema", []string{
		string(session.StateWorking),
		string(session.StatePrompt),
		string(session.StateTriage),
		string(session.StateDone),
	})
	out.WriteString("export type WorkerSessionState = z.infer<typeof workerSessionStateSchema>;\n\n")
	writeStringEnum(&out, "terminalSessionKinds", "terminalSessionKindSchema", []string{
		string(session.KindOrchestrator),
		string(session.KindWorker),
	})
	out.WriteString("export type TerminalSessionKind = z.infer<typeof terminalSessionKindSchema>;\n\n")
	writeObjectSchema(&out, "projectOrchestratorSchema", projectFields)
	out.WriteString("export type ProjectOrchestrator = z.infer<typeof projectOrchestratorSchema>;\n\n")
	writeObjectSchema(&out, "workerSessionSchema", sessionFields)
	out.WriteString("export type WorkerSession = z.infer<typeof workerSessionSchema>;\n")
	out.WriteString("export type WorkerAgent = WorkerSession['agent'];\n\n")
	writeObjectSchema(&out, "sessionWorkspaceSchema", workspaceFields)
	out.WriteString("export type SessionWorkspace = z.infer<typeof sessionWorkspaceSchema>;\n")

	return out.String(), nil
}

func writeStringEnum(out *bytes.Buffer, valuesName string, schemaName string, values []string) {
	fmt.Fprintf(out, "export const %s = [\n", valuesName)
	for _, value := range values {
		fmt.Fprintf(out, "  %s,\n", tsString(value))
	}
	fmt.Fprintf(out, "] as const;\n")
	fmt.Fprintf(out, "export const %s = z.enum(%s);\n", schemaName, valuesName)
}

func tsString(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "\\'") + "'"
}

func writeObjectSchema(out *bytes.Buffer, name string, fields []fieldSchema) {
	fmt.Fprintf(out, "export const %s = z.object({\n", name)
	for _, field := range fields {
		schema := field.Schema
		if field.Optional {
			schema += ".optional()"
		}
		fmt.Fprintf(out, "  %s: %s,\n", field.Name, schema)
	}
	fmt.Fprintf(out, "});\n")
}

func schemaFields(value reflect.Type) ([]fieldSchema, error) {
	fields := make([]fieldSchema, 0, value.NumField())
	for i := 0; i < value.NumField(); i++ {
		field := value.Field(i)
		jsonName, optional, ok := jsonField(field)
		if !ok {
			continue
		}

		schema, err := zodSchema(field.Type)
		if err != nil {
			return nil, fmt.Errorf("%s.%s: %w", value.Name(), field.Name, err)
		}
		fields = append(fields, fieldSchema{
			Name:     jsonName,
			Optional: optional,
			Schema:   schema,
		})
	}

	return fields, nil
}

func jsonField(field reflect.StructField) (string, bool, bool) {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", false, false
	}

	name, options, _ := strings.Cut(tag, ",")
	if name == "" {
		name = field.Name
	}

	return name, strings.Contains(","+options+",", ",omitempty,"), true
}

func zodSchema(value reflect.Type) (string, error) {
	switch value {
	case reflect.TypeOf(session.State("")):
		return "workerSessionStateSchema", nil
	case reflect.TypeOf(session.Kind("")):
		return "terminalSessionKindSchema", nil
	case reflect.TypeOf(session.Session{}):
		return "workerSessionSchema", nil
	case reflect.TypeOf(session.Project{}):
		return "projectOrchestratorSchema", nil
	}

	switch value.Kind() {
	case reflect.String:
		return "z.string()", nil
	case reflect.Bool:
		return "z.boolean()", nil
	case reflect.Slice:
		itemSchema, err := zodSchema(value.Elem())
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("z.array(%s)", itemSchema), nil
	default:
		return "", fmt.Errorf("unsupported type %s", value)
	}
}
